[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = ['ds-test/=lib/ds-test/src/','forge-std/=lib/forge-std/src/', '@openzeppelin/=lib/openzeppelin-contracts/contracts/']                                               # a list of remappings
optimize = true
optimize_runs = 1000

[rpc_endpoints]
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Add these lines to space out values
max_global_rejects = 1048576
shrink_sequence = 5000

# Add these new options
intensity = 100
max_seq_len = 100