[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = ['ds-test/=lib/ds-test/src/','forge-std/=lib/forge-std/src/', '@openzeppelin/=lib/openzeppelin-contracts/contracts/']                                               # a list of remappings


[rpc_endpoints]
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 1000